name: proyecto_dam
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  advance_pdf_viewer: ^2.0.1
  after_layout: ^1.1.0
  charts_flutter: ^0.12.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  google_maps_flutter: ^2.1.4
  permission_handler: ^9.0.2
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  url_launcher: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/img/
    - assets/img/walk/
    - assets/pdf/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
